### ISSUE TITLE
copy files to container fs

### ISSUE THREAD

**Issue by kovetskiy** [seletskiy/hastur#2]
I would prefer to use this for running integration tests, how I can copy files/directories to container filesystem?

**Comment by seletskiy** [comment]
Currently, there are no command for it, but files can be copied to container FS by using `cp`:

```bash
cp <file> <root>/containers/<container-name>/root/<target-path>
```

Where `<root>` is /usr/lib/hastur or value, passed by flag `-r`.

**Comment by kovetskiy** [comment]
it can be possible in runtime?

**Comment by seletskiy** [comment]
Yes, of course.

Note, that `root/` directory will only contains information specific to this container, e.g. will not contain all files from base package, but only files that was created while container was up and running.

If you want to observe root FS of container as a whole, consider checking `.nspawn.root/` dir instead of `root/` in the directory `<root>/containers/<container-name>`. Files, that will be created or modified inside `.nspawn.root` will be, actually, created inside `root/` and modified here.

BTW, handy command like `hastur -n <container-name> -F <source>:<target> <source>:<target> ...` will be really useful.

**Comment by kovetskiy** [comment]
Will you implement this feature?

**Comment by seletskiy** [comment]
I can add if you find it particulary useful.

**Comment by kovetskiy** [comment]
Yes, it should be useful.

Also I have another useful idea, do not remove ephemeral container if executed cmd exited with non-zero exit code.
